name: Deploy

on:
  push:
    branches:
      - main # O la rama que deseas desplegar

jobs:
  my-job:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        branch: gh-pages # O la rama en la que deseas implementar tu SPA
        folder: build # Carpeta de salida de la construcción de tu SPA
